import type { AuditFirm, FirmCategory, Tier } from "./types";

export const TIER_META: Readonly<
  Record<Tier, { label: string; color: string; description: string }>
> = {
  S: {
    label: "S Tier",
    color: "from-rose-500 to-orange-500",
    description:
      "업계 최상위. 대형 프로토콜의 표준이며 비용이 높고 대기열이 길다.",
  },
  "A+": {
    label: "A+ Tier",
    color: "from-orange-500 to-amber-500",
    description: "S에 근접한 강한 평판. 메이저 프로토콜에서 자주 선택된다.",
  },
  A: {
    label: "A Tier",
    color: "from-amber-500 to-yellow-500",
    description: "검증된 실력. 메이저 디파이 및 체인 프로젝트에서 신뢰받는 펌.",
  },
  B: {
    label: "B Tier",
    color: "from-emerald-500 to-teal-500",
    description:
      "합리적 가격대로 승부하는 미드티어, 과거 활발했으나 현재는 활동량이 줄어든 펌, 또는 잦은 클라이언트 해킹으로 명성이 떨어진 펌.",
  },
  C: {
    label: "C Tier",
    color: "from-sky-500 to-blue-500",
    description:
      "저가형 양산 오딧이거나, 트랙 레코드가 빈약하고 메이저 프로젝트 오딧 경험이 없는 펌.",
  },
};

export const CATEGORY_META: Readonly<
  Record<FirmCategory, { label: string; short: string; description: string }>
> = {
  "smart-contract": {
    label: "General Smart Contract",
    short: "Smart Contract",
    description: "일반적인 EVM 및 프로토콜 레이어 오딧을 주력으로 한다.",
  },
  cryptography: {
    label: "Cryptography & ZK",
    short: "Crypto / ZK",
    description: "ZK 회로, 암호 프리미티브, 저수준 수학적 정확성에 특화.",
  },
  "formal-verification": {
    label: "Formal Verification",
    short: "Formal Verif.",
    description: "수학적 명세 기반의 불변식 증명을 방법론으로 한다.",
  },
};

export const ORDERED_CATEGORIES: ReadonlyArray<FirmCategory> = [
  "smart-contract",
  "formal-verification",
  "cryptography",
];

export const AUDIT_FIRMS: ReadonlyArray<AuditFirm> = [
  {
    name: "Trail of Bits",
    tier: "S",
    category: "smart-contract",
    specialty: ["Smart Contract", "Cryptography", "Protocol"],
    notableClients: ["MakerDAO", "Compound", "Uniswap"],
    website: "https://www.trailofbits.com",
    notes: "보안 연구 깊이와 정형 검증 역량으로 유명.",
  },
  {
    name: "OpenZeppelin",
    tier: "S",
    category: "smart-contract",
    specialty: ["Smart Contract", "Standards", "DeFi"],
    notableClients: ["Compound", "Aave", "The Graph"],
    website: "https://www.openzeppelin.com",
    notes: "ERC 표준 라이브러리 메인테이너로 디파이 표준급.",
  },
  {
    name: "ConsenSys Diligence",
    tier: "A+",
    category: "smart-contract",
    specialty: ["Smart Contract", "EVM", "Internal"],
    notableClients: ["MetaMask", "Linea", "Aave (legacy)"],
    website: "https://consensys.io/diligence",
    notes: "최근 MetaMask와 Linea 등 ConsenSys 내부 프로덕트 위주로 활동.",
  },
  {
    name: "Spearbit",
    tier: "A+",
    category: "smart-contract",
    specialty: ["Smart Contract", "Boutique"],
    notableClients: ["Optimism", "ENS", "Connext"],
    website: "https://spearbit.com",
    notes: "최상위 독립 리서처 매칭 모델. 부티크 스타일 운영.",
  },
  {
    name: "Zellic",
    tier: "S",
    category: "smart-contract",
    specialty: ["Smart Contract", "L1/L2", "ZK"],
    notableClients: ["Sui", "Aptos", "MystenLabs"],
    website: "https://www.zellic.io",
    notes: "CTF 출신 리서처 중심. L1/L2와 ZK에 강점이 있다.",
  },
  {
    name: "ChainSecurity",
    tier: "A+",
    category: "smart-contract",
    specialty: ["Smart Contract", "Formal Verification", "DeFi"],
    notableClients: ["Curve", "Lido", "Yearn"],
    website: "https://chainsecurity.com",
    notes: "스위스 ETH 취리히 출신. 학술적 깊이와 정형 분석 도구.",
  },
  {
    name: "Asymmetric Research",
    tier: "S",
    category: "smart-contract",
    specialty: ["Smart Contract", "Bridge", "L1/L2"],
    notableClients: ["Wormhole", "Jito", "MystenLabs"],
    website: "https://www.asymmetric.re",
    notes:
      "ex-Jump 등 엘리트 리서처 그룹. 하이스테이크 인시던트 분석으로 명성.",
  },
  {
    name: "Certora",
    tier: "S",
    category: "formal-verification",
    specialty: ["Formal Verification"],
    notableClients: ["Aave", "Compound", "Lido"],
    website: "https://www.certora.com",
    notes: "정형 검증 특화. CVL 스펙으로 불변식을 증명한다.",
  },

  {
    name: "Cantina",
    tier: "A+",
    category: "smart-contract",
    specialty: ["Audit Contest", "Boutique"],
    notableClients: ["Wormhole", "EigenLayer"],
    website: "https://cantina.xyz",
    notes: "Spearbit 마켓플레이스 후신. 톱티어 리서처 풀 보유.",
  },
  {
    name: "Halborn",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "Infra", "Pentest"],
    notableClients: ["Solana", "Avalanche", "THORChain"],
    website: "https://www.halborn.com",
    notes: "스마트컨트랙트와 인프라 펜테스트를 통합 제공.",
  },
  {
    name: "Sigma Prime",
    tier: "S",
    category: "smart-contract",
    specialty: ["Consensus", "L1", "Rust"],
    notableClients: ["Ethereum Foundation", "Lighthouse"],
    website: "https://sigmaprime.io",
    notes: "이더리움 합의/클라이언트 분야 최고 권위.",
  },
  {
    name: "Code4rena",
    tier: "A",
    category: "smart-contract",
    specialty: ["Audit Contest"],
    notableClients: ["ENS", "Connext", "Olympus"],
    website: "https://code4rena.com",
    notes: "공개 컨테스트 형식. 다수의 시각이 강점이다.",
  },
  {
    name: "Sherlock",
    tier: "A",
    category: "smart-contract",
    specialty: ["Audit Contest", "Coverage"],
    notableClients: ["LayerZero", "Perennial", "Symmetric"],
    website: "https://www.sherlock.xyz",
    notes: "컨테스트와 보험 커버리지를 결합한 모델.",
  },
  {
    name: "Macro",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "Boutique"],
    notableClients: ["Optimism", "Reserve", "Worldcoin"],
    website: "https://0xmacro.com",
    notes: "ex-Coinbase 엔지니어들이 설립한 부티크.",
  },
  {
    name: "Dedaub",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "Static Analysis", "EVM"],
    notableClients: ["Lido", "Yearn", "Chainlink"],
    website: "https://dedaub.com",
    notes: "Watchdog 디컴파일러로 알려진 정적 분석 강점.",
  },
  {
    name: "Quantstamp",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Maker", "Solana", "BNB Chain"],
    website: "https://quantstamp.com",
    notes: "초기 디파이 오딧 펌. 광범위한 포트폴리오 보유.",
  },
  {
    name: "Ottersec",
    tier: "A+",
    category: "smart-contract",
    specialty: ["Solana", "Move", "ZK"],
    notableClients: ["Jito", "Marginfi", "Drift"],
    website: "https://osec.io",
    notes: "Solana와 Move 생태계에서 빠르게 평판을 구축.",
  },
  {
    name: "Pashov Audit Group",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "Boutique"],
    notableClients: ["Ethena", "Karak", "Sofamon"],
    website: "https://www.pashov.net",
    notes: "Krum Pashov가 이끄는 부티크. 빠른 회전과 높은 적중률.",
  },
  {
    name: "Electisec",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi", "ZK"],
    notableClients: ["Yearn", "Cap", "Cove"],
    website: "https://electisec.tech",
    notes:
      "구 yAudit과 yAcademy의 리브랜드. 펠로우십을 통한 독립 리서처 풀과 부티크 오딧 결합.",
  },
  {
    name: "Recon",
    tier: "A",
    category: "smart-contract",
    specialty: ["Invariant Testing", "Fuzzing", "Smart Contract"],
    notableClients: ["Liquity", "Centrifuge", "Badger", "Balancer"],
    website: "https://getrecon.xyz",
    notes:
      "Echidna, Medusa, Halmos 기반 invariant 테스팅 특화. 수동 리뷰가 놓치는 회계/경제 버그에 강하다.",
  },
  {
    name: "Cyfrin",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "Education", "Tooling"],
    notableClients: ["Beanstalk", "Eigen Foundation"],
    website: "https://www.cyfrin.io",
    notes: "Patrick Collins 주축. Aderyn 정적 분석기 메인테이너.",
  },
  {
    name: "Nethermind Security",
    tier: "A+",
    category: "cryptography",
    specialty: ["Smart Contract", "L1/L2", "Formal Verification"],
    notableClients: ["Starknet", "Aave"],
    website: "https://www.nethermind.io",
    notes: "Nethermind 클라이언트 팀의 보안 부서. Cairo와 EVM 모두 커버.",
  },
  {
    name: "ChainLight",
    tier: "A+",
    category: "smart-contract",
    specialty: ["Smart Contract", "Bridge", "L1/L2"],
    notableClients: ["Optimism", "Polygon", "Abstract"],
    website: "https://chainlight.io",
    notes: "한국 기반 보안 리서치 팀. 웹2 보안 회사 티오리(Theori) 산하.",
  },
  {
    name: "Three Sigma",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "Quant", "DeFi"],
    notableClients: ["Maple Finance", "GMX"],
    website: "https://threesigma.xyz",
    notes: "정량 분석 결합 오딧. 금융 모델링 검증에 강하다.",
  },
  {
    name: "Sec3",
    tier: "B",
    category: "smart-contract",
    specialty: ["Solana", "Audit-as-a-Service"],
    notableClients: ["Drift", "Mango", "MarginFi"],
    website: "https://www.sec3.dev",
    notes: "Solana 특화 자동화 분석 도구 X-ray와 결합한 오딧.",
  },
  {
    name: "Statemind",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["1inch", "Lido", "Curve"],
    website: "https://statemind.io",
    notes: "디파이와 LSD 영역에서 두각. 구체적 익스플로잇 시연 빈번.",
  },
  {
    name: "Oak Security",
    tier: "A",
    category: "smart-contract",
    specialty: ["Cosmos", "CosmWasm", "Smart Contract"],
    notableClients: ["Osmosis", "Mars Protocol"],
    website: "https://www.oaksecurity.io",
    notes: "Cosmos와 CosmWasm 생태계의 사실상 표준 펌.",
  },
  {
    name: "BlockSec",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "Phalcon", "Monitoring"],
    notableClients: ["Compound", "Trader Joe"],
    website: "https://blocksec.com",
    notes: "Phalcon 모니터링 도구로 잘 알려진 보안 그룹.",
  },
  {
    name: "Ackee Blockchain",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "Solana", "Tooling"],
    notableClients: ["Lido", "Trezor"],
    website: "https://ackeeblockchain.com",
    notes: "Wake 도구 메인테이너. EVM과 Solana 모두 커버.",
  },
  {
    name: "Renascence Labs",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "Boutique"],
    notableClients: ["Bunni", "Ekubo"],
    website: "https://renascence.io",
    notes: "디파이 메카닉 분석 부티크. 작은 규모지만 평이 좋다.",
  },
  {
    name: "Trust Security",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "Boutique", "EVM"],
    notableClients: ["Various DeFi", "Solo audits"],
    website: "https://www.trust-security.xyz",
    notes: "Trust1995(Anatomist) 솔로 오딧 명성에서 출발한 부티크.",
  },
  {
    name: "Guardian Audits",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["GMX", "Arbitrum ecosystem"],
    website: "https://guardianaudits.com",
    notes: "DeFi 특화 부티크. Arbitrum 생태계에서 활발.",
  },
  {
    name: "Paladin",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi", "Boutique"],
    notableClients: ["LayerZero", "Trader Joe", "Avalanche"],
    website: "https://paladinsec.co",
    notes: "DeFi 특화 부티크. 프리랜스 리서처 네트워크 모델.",
  },
  {
    name: "Least Authority",
    tier: "A+",
    category: "cryptography",
    specialty: ["Cryptography", "ZK", "Privacy"],
    notableClients: ["Tezos", "Filecoin", "Ethereum 2.0"],
    website: "https://leastauthority.com",
    notes: "암호학과 프라이버시 영역 베테랑. ZK와 프로토콜 레벨 강점.",
  },
  {
    name: "Runtime Verification",
    tier: "S",
    category: "formal-verification",
    specialty: ["Formal Verification", "EVM"],
    notableClients: ["Ethereum Foundation", "DappHub"],
    website: "https://runtimeverification.com",
    notes: "K Framework 기반의 형식 의미론.",
  },
  {
    name: "Informal Systems",
    tier: "A+",
    category: "formal-verification",
    specialty: ["Formal Verification", "Cosmos", "TLA+"],
    notableClients: ["Cosmos Hub", "Tendermint", "Injective", "Agoric"],
    website: "https://informal.systems",
    notes:
      "Apalache TLA+ 모델 체커 메인테이너. Cosmos와 Tendermint 생태계의 사실상 표준 정형 검증 펌.",
  },
  {
    name: "Veridise",
    tier: "S",
    category: "cryptography",
    specialty: ["ZK", "Circuits", "Formal Verification"],
    notableClients: ["Aleo", "Polygon zkEVM"],
    website: "https://veridise.com",
    notes: "ZK 회로 검증 특화. 학술적 백그라운드가 강하다.",
  },
  {
    name: "Hexens",
    tier: "A+",
    category: "smart-contract",
    specialty: ["Smart Contract", "ZK", "Pentest"],
    notableClients: ["Polygon", "Lens", "1inch"],
    website: "http://hexens.io",
    notes: "ZK와 EVM 모두 커버. 회로 분석 역량으로 알려짐.",
  },
  {
    name: "ABDK Consulting",
    tier: "A",
    category: "cryptography",
    specialty: ["Smart Contract", "Math", "Cryptography"],
    notableClients: ["1inch", "Origin Protocol"],
    website: "https://abdk.consulting",
    notes: "수학적 정확성과 가스 최적화 라이브러리로 유명.",
  },

  {
    name: "PeckShield",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "Threat Intel"],
    notableClients: ["BNB Chain ecosystem"],
    website: "https://peckshield.com",
    notes: "온체인 위협 인텔리전스 트윗으로 유명.",
  },
  {
    name: "SlowMist",
    tier: "B",
    category: "smart-contract",
    specialty: ["Threat Intel", "Wallet"],
    notableClients: ["Binance", "OKX", "Huobi"],
    website: "https://www.slowmist.com",
    notes: "아시아권 인시던트 추적과 대응에 강점.",
  },
  {
    name: "Hacken",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "CEX"],
    notableClients: ["Polygon", "Huobi", "VeChain"],
    website: "https://hacken.io",
    notes: "광범위한 서비스 제공. 거래소와 지갑 영역 활동이 많다.",
  },
  {
    name: "QuillAudits",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "L2"],
    notableClients: ["Polygon", "0x"],
    website: "https://www.quillaudits.com",
    notes: "회전이 빠른 미드티어. 인도 기반의 큰 운영 규모.",
  },
  {
    name: "Salus",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "ZK"],
    notableClients: ["Linea", "Manta"],
    website: "https://salusec.io",
    notes: "ZK 영역에서 활동. 실리콘밸리 출신 리서처 다수.",
  },
  {
    name: "Iosiro",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Synthetix", "Kwenta"],
    website: "https://www.iosiro.com",
    notes: "Synthetix 생태계 깊은 이해. 남아공 기반.",
  },
  {
    name: "Composable Security",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Beefy", "Mean Finance"],
    website: "https://composable-security.com",
    notes: "EU 기반 부티크. 전문 도메인이 좁고 깊은 편.",
  },
  {
    name: "Pessimistic",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["1inch", "Curve", "Pickle"],
    website: "https://pessimistic.io",
    notes: "역사가 긴 러시아 기반 펌. 견고한 결과물.",
  },
  {
    name: "BAIL Security",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Various mid-cap DeFi"],
    website: "https://www.bailsec.io",
    notes: "신생 부티크. 소규모 디파이 프로젝트 회전이 잦다.",
  },
  {
    name: "MixBytes",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Lido", "1inch", "Yearn"],
    website: "https://mixbytes.io",
    notes: "오랜 경력의 EU/CIS 기반 펌. 디파이 광범위 커버.",
  },
  {
    name: "Solidified",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "Marketplace"],
    notableClients: ["TheGraph", "BarnBridge"],
    website: "https://solidified.io",
    notes: "초기 디파이 시기 활발. 마켓플레이스 모델.",
  },
  {
    name: "Coinfabrik",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "Substrate"],
    notableClients: ["RIF", "Polkadot ecosystem"],
    website: "https://www.coinfabrik.com",
    notes: "남미 기반의 베테랑. RSK와 Polkadot에 강점.",
  },
  {
    name: "Coinspect",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "Wallet", "Pentest"],
    notableClients: ["MetaMask", "Argent"],
    website: "https://www.coinspect.com",
    notes: "지갑과 모바일 보안에 특화한 베테랑 부티크.",
  },
  {
    name: "Decurity",
    tier: "A",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Convex", "Frax"],
    website: "https://decurity.io",
    notes: "디파이 메카닉 깊은 이해. 작은 규모의 정밀 부티크.",
  },
  {
    name: "Hashlock",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Pendle", "Various"],
    website: "https://hashlock.com",
    notes: "호주 기반의 미드티어 펌. 합리적 가격대.",
  },
  {
    name: "Resonance Security",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "Infra", "Pentest"],
    notableClients: ["Various"],
    website: "https://www.resonance.security",
    notes: "구 Cyber Unit. 인프라와 컨트랙트를 통합 제공.",
  },
  {
    name: "Sayfer",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "Pentest"],
    notableClients: ["Various"],
    website: "https://sayfer.io",
    notes: "이스라엘 기반. CTF 출신 리서처 다수.",
  },
  {
    name: "Omniscia",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Various DeFi"],
    website: "https://omniscia.io",
    notes: "DeFi 위주의 일반 미드티어 펌.",
  },
  {
    name: "Bunzz Audit",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "Hybrid"],
    notableClients: ["Japanese Web3 ecosystem"],
    website: "https://www.bunzz.dev",
    notes: "일본 기반. 자동화 분석과 수동 리뷰 결합 모델.",
  },
  {
    name: "MoveBit",
    tier: "A+",
    category: "smart-contract",
    specialty: ["Move", "Aptos", "Sui"],
    notableClients: ["Aptos ecosystem", "Sui ecosystem"],
    website: "https://www.movebit.xyz",
    notes: "BitsLab 산하의 Move 언어 특화 펌.",
  },
  {
    name: "TonBit",
    tier: "A",
    category: "smart-contract",
    specialty: ["TON", "FunC"],
    notableClients: ["TON ecosystem"],
    website: "https://www.tonbit.xyz",
    notes: "BitsLab 산하의 TON 생태계 특화 펌.",
  },
  {
    name: "Zokyo",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Various DeFi"],
    website: "https://zokyo.io",
    notes: "북미 기반 미드티어. 광범위한 보안 서비스 제공.",
  },
  {
    name: "WatchPug",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Various"],
    website: "https://www.watchpug.org",
    notes: "오랜 활동의 미드티어 부티크.",
  },
  {
    name: "Oxorio",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Various EU DeFi"],
    website: "https://oxor.io",
    notes: "EU 기반 미드티어 펌.",
  },
  {
    name: "ScaleBit",
    tier: "B",
    category: "smart-contract",
    specialty: ["L2", "Scaling", "Smart Contract"],
    notableClients: ["Various L2"],
    website: "https://www.scalebit.xyz",
    notes: "BlockSec 산하의 스케일링 특화 펌.",
  },
  {
    name: "BlockApex",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://blockapex.io",
    notes: "파키스탄 기반 미드티어. 합리적 가격대.",
  },
  {
    name: "SharkTeam",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "Threat Intel"],
    notableClients: ["Asian ecosystem"],
    website: "https://www.sharkteam.org",
    notes: "아시아권 위협 인텔리전스 결합 오딧.",
  },
  {
    name: "Blaize.security",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Various"],
    website: "https://blaize.tech",
    notes: "우크라이나 기반 미드티어. 디파이 광범위 커버.",
  },
  {
    name: "MetaTrust Labs",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "AI Tooling"],
    notableClients: ["Various"],
    website: "https://metatrust.io",
    notes: "싱가포르 기반. AI 보조 분석 강조.",
  },
  {
    name: "Softstack",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://www.softstack.io",
    notes: "EU 기반 미드티어 펌.",
  },
  {
    name: "Verilog Solutions",
    tier: "C",
    category: "formal-verification",
    specialty: ["Formal Verification", "Smart Contract"],
    notableClients: ["Various"],
    website: "https://www.verilog.solutions",
    notes: "정형 분석을 표방하는 미드티어. 학술적 톤.",
  },
  {
    name: "Security Research Labs",
    tier: "B",
    category: "smart-contract",
    specialty: ["Pentest", "Smart Contract", "Infra"],
    notableClients: ["Various"],
    website: "https://www.srlabs.de",
    notes: "독일 SRLabs. 일반 보안에서 Web3로 확장.",
  },
  {
    name: "Verichains",
    tier: "A+",
    category: "cryptography",
    specialty: ["Smart Contract", "Cryptography"],
    notableClients: ["Ronin", "BNB Chain"],
    website: "https://www.verichains.io",
    notes: "베트남 기반. 암호학 백그라운드 강하며 Ronin 사고 분석 참여.",
  },

  {
    name: "CertiK",
    tier: "B",
    category: "smart-contract",
    specialty: ["Smart Contract", "Skynet", "Web2"],
    notableClients: ["Wide BSC and altcoin coverage"],
    website: "https://www.certik.com",
    notes:
      "SC 오딧은 결과물 품질 편차 비판이 있으나, Web2 오딧 팀(Skynet)이 최근 의미 있는 활동을 보이고 있다.",
  },
  {
    name: "Beosin",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "Compliance"],
    notableClients: ["Aptos ecosystem", "Bytetrade"],
    website: "https://beosin.com",
    notes: "아시아권 중소 프로젝트 상대 활동. 광범위한 포트폴리오.",
  },
  {
    name: "Solidity Finance",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Mid-cap DeFi"],
    website: "https://solidity.finance",
    notes: "저가 빠른 턴어라운드 모델. 스코프가 좁은 편이다.",
  },
  {
    name: "SmartState",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various small-cap"],
    website: "https://smartstate.tech",
    notes: "소형 프로젝트 위주 활동. 진입 가격대가 낮다.",
  },
  {
    name: "BlockSafu",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "BSC"],
    notableClients: ["Various BSC tokens"],
    website: "https://www.blocksafu.com",
    notes: "BSC 토큰 위주의 저가 옵션.",
  },
  {
    name: "Audit One",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Smaller protocols"],
    website: "https://audit.one",
    notes: "스테이킹 사업자 부속 보안 서비스. 저가 옵션.",
  },
  {
    name: "DeFiSafety",
    tier: "C",
    category: "smart-contract",
    specialty: ["Process Review", "Rating"],
    notableClients: ["DeFi protocols (process audits)"],
    website: "https://defisafety.com",
    notes: "보안 감사가 아닌 프로세스 성숙도 점수화 서비스.",
  },
  {
    name: "Red4Sec",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "Pentest"],
    notableClients: ["Various"],
    website: "https://red4sec.com",
    notes: "스페인 기반 일반 보안 펌. Web3 영역도 커버.",
  },
  {
    name: "Armors",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "AI"],
    notableClients: ["Various"],
    website: "https://armors.ai",
    notes: "AI 보조 분석을 강조하는 신생 펌.",
  },
  {
    name: "Team Omega",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://teamomega.eth.limo",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "DeFiMoon",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "DeFi"],
    notableClients: ["Various small DeFi"],
    website: "https://defimoon.org",
    notes: "신생 디파이 mass-market 펌.",
  },
  {
    name: "0xGuard",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "Token"],
    notableClients: ["Various tokens"],
    website: "https://0xguard.com",
    notes: "토큰 발행자 위주의 mass-market.",
  },
  {
    name: "Rugdog",
    tier: "C",
    category: "smart-contract",
    specialty: ["Token Screening"],
    notableClients: ["Various tokens"],
    website: "https://rugdog.net",
    notes: "rug 감지 토큰 스크리닝 서비스.",
  },
  {
    name: "Securr",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://securr.tech",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "Audita",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://audita.io",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "Monethic",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://monethic.io",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "Advix",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "AI"],
    notableClients: ["Various"],
    website: "https://advix.ai",
    notes: "AI 강조 신생 펌.",
  },
  {
    name: "Mosaia",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://mosaia.io",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "Hakflow",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://hakflow.com",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "SCV Security",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://scv.services",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "0xTeam",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://0xteam.com",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "BugBlow",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://bugblow.com",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "SecureDApp",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://securedapp.io",
    notes: "인도 기반 mass-market 펌.",
  },
  {
    name: "Safe Edges",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://safeedges.in",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "Perimeter",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://perimetersec.io",
    notes: "신생 부티크.",
  },
  {
    name: "Null Return",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://nullreturn.io",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "ChainAudits",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://chainaudits.com",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "Adevar Labs",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://adevarlabs.com",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "Sub 7 Security",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://sub7.tech",
    notes: "신생 mass-market 펌.",
  },
  {
    name: "TechRate",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "BSC"],
    notableClients: ["BSC and altcoin tokens"],
    website: "https://techrate.org",
    notes: "BSC와 SCAN 토큰 위주의 저가 mass-market.",
  },
  {
    name: "Cyberscope",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "KYC"],
    notableClients: ["Various tokens"],
    website: "https://www.cyberscope.io",
    notes: "KYC와 오딧을 결합한 토큰 발행자 대상 서비스.",
  },
  {
    name: "Solidproof",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various tokens"],
    website: "https://solidproof.io",
    notes: "독일 기반의 저가 펌. 빠른 회전과 표준 보고서.",
  },
  {
    name: "Hashex",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://hashex.org",
    notes: "CIS 기반의 저가 옵션. 광범위한 토큰 커버.",
  },
  {
    name: "InterFi Network",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract", "BSC"],
    notableClients: ["BSC tokens"],
    website: "https://www.interfi.network",
    notes: "BSC mass-market. 발행자 친화적인 보고서 스타일.",
  },
  {
    name: "Shellboxes",
    tier: "C",
    category: "smart-contract",
    specialty: ["Smart Contract"],
    notableClients: ["Various"],
    website: "https://shellboxes.com",
    notes: "모로코 기반의 저가 펌. 빠른 회전이 특징.",
  },
];

export function firmsByTier(tier: Tier): ReadonlyArray<AuditFirm> {
  return AUDIT_FIRMS.filter((f) => f.tier === tier);
}

export function firmsByTierAndCategory(
  tier: Tier,
  category: FirmCategory,
): ReadonlyArray<AuditFirm> {
  return AUDIT_FIRMS.filter((f) => f.tier === tier && f.category === category);
}

export const ORDERED_TIERS: ReadonlyArray<Tier> = ["S", "A+", "A", "B", "C"];
